### ISSUE TITLE
Azure Speech compatibility with Mac

### ISSUE THREAD

**Issue by adamhbz** [Rtyper/LipSync-Pro#2]
`Assets/Rogo Digital 1/LipSync Pro/AutoSync/Editor/Modules/Azure Speech Recognition/ASAzureSpeechRecognitionModule.cs(9,17): error CS0234: The type or namespace name 'CognitiveServices' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)`

I get this error when opening on a Mac.

**Comment by Rtyper** [comment]
It may be that I only included the Speech SDK for Windows in there. If you don't need that module you can just delete it, otherwise have a look on Microsoft's site - you may need to download a different version of the SDK and swap it out.

**Comment by adamhbz** [comment]
Hi yes, it seems fine to delete it.

I looked into using it but I think there's a few hopes to jump through for a Mac user.
