### ISSUE TITLE
Montreal Forced Aligner path is not verified...

### ISSUE THREAD

**Issue by adamhbz** [Rtyper/LipSync-Pro#4]
![image](https://user-images.githubusercontent.com/13640398/128018086-76a4aafb-9af2-4e06-838c-a21228168d85.png)

**Comment by adamhbz** [comment]
Im trying to run in the  Window because I can't get the AutoSync to work but this is giving me another error. Maybe it will help solve the other issues.

I checked the path and it looks correct.

**Comment by Rtyper** [comment]
Have you clicked the "Verify" button next to the path in the settings screen? If it's correct, you should get a green light next to the path and this error won't appear. If you're just setting it up for the first time, make sure you've followed the instructions in the docs, including running the AutoSync Setup Wizard.

**Comment by adamhbz** [comment]
Hi thank you for getting back to me.

I didn't know about the settings but have now found it. 

I created a new project just for the audio processing, so did a fresh LipSync pro install and ran the wizard.

Everything looks ok and all of the paths point to the original locations which seem correct. I also tried manually browsing and selecting the file that was in the original path.

BUT the Verify button does nothing and the light is RED.


This is the path: "/Users/adam/_BZ/Test/Assets/Rogo Digital/LipSync Pro/AutoSync/Editor/Modules/Montreal Forced Aligner/montreal-forced-aligner-mac/lib/align"

If you look at the screenshots you will see it is correct.

Here is a couple of screen shots:

![image](https://user-images.githubusercontent.com/13640398/128141055-c348d079-aa4c-46e6-8a17-0a2c24208512.png)

![Screenshot 2021-08-04 at 08 27 36](https://user-images.githubusercontent.com/13640398/128141087-6ca72384-0de4-41a8-b75d-2b155f505684.png)


Please let me know if there is anything else I could try.

**Comment by adamhbz** [comment]
Could it be that my Mac is an newer Silicon Mac?

**Comment by adamhbz** [comment]
I removed the Github version and installed from my existing Asset Store asset and everything seems to be working.

**Comment by a9a4k** [comment]
Was able to make it work with github version. On mac you have to give permission to executable by running
```
chmod 777 <path-to-your-project>/Assets/Rogo\ Digital/LipSync\ Pro/AutoSync/Editor/Modules/Montreal\ Forced\ Aligner/montreal-forced-aligner-mac/lib/align
```
